#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Artisan Console Entry Point
|--------------------------------------------------------------------------
|
| Artisan is a command line interface included with Laravel. It provides
| a number of helpful commands for your application.
|
*/

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput));
